### ISSUE TITLE
Beautiful Soup missing

### ISSUE THREAD

**Issue by jsimpsonjr00** [skram/plugin.video.animebakatv#1]
ADB pushed the addon to my FireTV stick. Get an error on run:

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.ImportError'>
  Error Contents: No module named BeautifulSoup
  Traceback (most recent call last):
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.animebakatv/default.py", line 22, in <module> from resources.lib import abtv
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.animebakatv/resources/lib/abtv.py", line 12, in <module>
     from BeautifulSoup import BeautifulSoup
     ImportError: No module named BeautifulSoup
  ->End of Python script error report<--

I'm also working on an Animebaka.tv addon. New to python and Kodi dev. I just threw it together in between work projects so the code is a little rough.

**Comment by skram** [comment]
May be due to the fact I didn't have the version #'s for the dependencies in addon.xml, i added those. Also in the dev. branch I have it pulling fanart from TheTVDB, so pull that branch and let me know if it's working for you. 0073cd45f6a78569b26d6b388f1fb5e6294061e5 @jsimpsonjr00 

I'll check out your's!

**Comment by jsimpsonjr00** [comment]
I tried the dev branch. Turns out this was my fault for adb pushing, as I've been doing with my own, rather than installing from zip. I didn't realize Kodi would need to install the dependencies and adb push wouldn't suffice.

Although the included zip does not have a correct file structure. So I remade it removing the extra folders in the hierarchy, put it up on my network and was able to install to the FireTV stick just fine. It suppose it's easiest to just download the project as a zip and install from that.

I like that you have the latest updates which is great for following ongoing shows especially. I use Crunchyroll mainly like that using the last updated to follow the simulcasts. You have a feature mine lacks and was looking at adding today. I've basically implemented the rest of the website as far as videos go though, so it has a lot of functionality.

I've not looked at your source closely, but you can get series/show/movie art if you have the ID animebaka uses. If you scrape links it's usually on a data-show-id attribute. Then the artwork is named a few different ways depending on the size of the image something like images.animebaka.tv/a_lcap/<Show ID>_lcap.jpg or images.animebaka.tv/a_lth/<Show ID>_lth.jpg I'm using those and you might see a performance improvement by knowing their naming convention.

Closing this issue, since it was my mistake. Thanks for the add on!
